# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segger_jlink.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame, QMainWindow, QStatusBar


class Segger_Dialog(object):
    def setupUi(self, frame, width):
        """
            Jlink/CMSIS-DAP SEGGER RTT打印调试，数据发送，烧录
        """
        # 第4个布局
        main_frame4 = QMainWindow()
        frame4_bar = QStatusBar()
        frame4_bar.setObjectName("frame4_bar")
        main_frame4.setStatusBar(frame4_bar)
        frame4_bar.showMessage("欢迎进入segger工具")

        self.segger_frame = QFrame(main_frame4)
        self.segger_frame.setGeometry(0, 0, width, frame.height() - 25)
        self.segger_frame.setFrameShape(QFrame.Panel)
        self.segger_frame.setFrameShadow(QFrame.Raised)

        self.gridLayout = QtWidgets.QGridLayout(self.segger_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.segger_frame)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 4, 1, 2)
        self.label = QtWidgets.QLabel(self.segger_frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.segger_frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.segger_wave_check = QtWidgets.QCheckBox(self.segger_frame)
        self.segger_wave_check.setObjectName("segger_wave_check")
        self.gridLayout.addWidget(self.segger_wave_check, 2, 8, 1, 1)
        self.segger_hexdisp_check = QtWidgets.QCheckBox(self.segger_frame)
        self.segger_hexdisp_check.setObjectName("segger_hexdisp_check")
        self.gridLayout.addWidget(self.segger_hexdisp_check, 4, 8, 1, 1)
        self.segger_hexsend_check = QtWidgets.QCheckBox(self.segger_frame)
        self.segger_hexsend_check.setObjectName("segger_hexsend_check")
        self.gridLayout.addWidget(self.segger_hexsend_check, 5, 8, 1, 1)
        self.segger_program_btn = QtWidgets.QPushButton(self.segger_frame)
        self.segger_program_btn.setObjectName("segger_program_btn")
        self.gridLayout.addWidget(self.segger_program_btn, 7, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.segger_frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 4, 1, 1)
        self.segger_rttmap_tbtn = QtWidgets.QToolButton(self.segger_frame)
        self.segger_rttmap_tbtn.setObjectName("segger_rttmap_tbtn")
        self.gridLayout.addWidget(self.segger_rttmap_tbtn, 2, 6, 1, 1)
        self.segger_send_data_line = QtWidgets.QLineEdit(self.segger_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segger_send_data_line.sizePolicy().hasHeightForWidth())
        self.segger_send_data_line.setSizePolicy(sizePolicy)
        self.segger_send_data_line.setObjectName("segger_send_data_line")
        self.gridLayout.addWidget(self.segger_send_data_line, 4, 0, 2, 7)
        self.segger_rttmap_rbtn = QtWidgets.QRadioButton(self.segger_frame)
        self.segger_rttmap_rbtn.setObjectName("segger_rttmap_rbtn")
        self.gridLayout.addWidget(self.segger_rttmap_rbtn, 1, 5, 1, 1)
        self.segger_jlinkarm_line = QtWidgets.QLineEdit(self.segger_frame)
        self.segger_jlinkarm_line.setObjectName("segger_jlinkarm_line")
        self.gridLayout.addWidget(self.segger_jlinkarm_line, 2, 0, 1, 1)
        self.segger_disp_text = QtWidgets.QTextEdit(self.segger_frame)
        self.segger_disp_text.setObjectName("segger_disp_text")
        self.gridLayout.addWidget(self.segger_disp_text, 0, 0, 1, 9)
        self.segger_program_line = QtWidgets.QLineEdit(self.segger_frame)
        self.segger_program_line.setObjectName("segger_program_line")
        self.gridLayout.addWidget(self.segger_program_line, 7, 0, 1, 7)
        self.segger_jlinkarm_tbtn = QtWidgets.QToolButton(self.segger_frame)
        self.segger_jlinkarm_tbtn.setObjectName("segger_jlinkarm_tbtn")
        self.gridLayout.addWidget(self.segger_jlinkarm_tbtn, 2, 1, 1, 1)
        self.segger_send_btn = QtWidgets.QPushButton(self.segger_frame)
        self.segger_send_btn.setObjectName("segger_send_btn")
        self.gridLayout.addWidget(self.segger_send_btn, 5, 7, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.segger_frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.segger_mcu_combox = QtWidgets.QComboBox(self.segger_frame)
        self.segger_mcu_combox.setObjectName("segger_mcu_combox")
        self.gridLayout.addWidget(self.segger_mcu_combox, 2, 2, 1, 1)
        self.segger_link_btn = QtWidgets.QPushButton(self.segger_frame)
        self.segger_link_btn.setObjectName("segger_link_btn")
        self.gridLayout.addWidget(self.segger_link_btn, 2, 7, 1, 1)
        self.segger_clear_btn = QtWidgets.QPushButton(self.segger_frame)
        self.segger_clear_btn.setObjectName("segger_clear_btn")
        self.gridLayout.addWidget(self.segger_clear_btn, 4, 7, 1, 1)

        self.retranslateUi()

        frame4_bar_frame = QFrame(main_frame4)
        frame4_bar_frame.setGeometry(0, frame.height(), width, 25)

        return main_frame4, self.segger_frame

    def retranslateUi(self):
        self.label.setText("jlinkARM.dll路径")
        self.label_3.setText("填入发送数据")
        self.segger_wave_check.setText("波形显示")
        self.segger_hexdisp_check.setText("Hex显示")
        self.segger_hexsend_check.setText("Hex发送")
        self.segger_program_btn.setText("烧录")
        self.label_2.setText("RTT LOG地址")
        self.segger_rttmap_tbtn.setText("...")
        self.segger_rttmap_rbtn.setText(".map路径")
        self.segger_jlinkarm_tbtn.setText("...")
        self.segger_send_btn.setText("发送")
        self.label_4.setText("烧录文件路径")
        self.segger_link_btn.setText("连接")
        self.segger_clear_btn.setText("清除数据")



